### ISSUE TITLE
User key '/root/.android/adbkey' does not exist

### ISSUE THREAD

**Issue by urusha** [hassio-addons/addon-adb#11]
# Problem/Motivation

Not starting, getting this in log, no matter if `keys_path` is configured:
```
[20:52:01] INFO: Starting the Android Debug Bridge server...
adb I 05-07 12:52:01  1005  1005 adb_auth_host.cpp:416] adb_auth_init...
adb I 05-07 12:52:01  1005  1005 adb_auth_host.cpp:262] User key '/root/.android/adbkey' does not exist...
adb I 05-07 12:52:01  1005  1005 adb_auth_host.cpp:109] generate_key(/root/.android/adbkey)...
[12:52:02] TRACE: bashio::config.has_value: keys_path
[12:52:02] TRACE: bashio::config: keys_path
[12:52:02] TRACE: bashio::jq: /data/options.json if (.keys_path == null) then
            null
        elif (.keys_path | type == "string") then
            .keys_path // empty
        elif (.keys_path | type == "boolean") then
            .keys_path // false
        elif (.keys_path | type == "array") then
            if (.keys_path == []) then
                empty
            else
                .keys_path[]
            end
        elif (.keys_path | type == "object") then
            if (.keys_path == {}) then
                empty
            else
                .keys_path
            end
        else
            .keys_path
        end
[12:52:02] TRACE: bashio::fs.file_exists: /data/adbkey
[12:52:03] INFO: Starting the Android Debug Bridge server...
adb I 05-07 12:52:03  1025  1025 adb_auth_host.cpp:416] adb_auth_init...
...
```

## Expected behavior

ADB server is started

## Actual behavior

ADB server is not started, getting errors

## Steps to reproduce

Pi 3, hassio 89.1, addon-adb 0.4.0, install and start.

```
{
  "log_level" : "trace",
  "devices": [
    "192.168.1.2"
  ],
  "reconnect_timeout": 90
}
```

**Comment by e-krebs** [comment]
I'm having the same here, it's looping through these logs non-stop

**Comment by sinclairpaul** [comment]
Can you update the issue with your hardware platform details?, i.e. this part of the log

 Hass.io Add-on: ADB - Android Debug Bridge
 The Android Debug Bridge server program

 Add-on version: 0.4.0
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.2 LTS  (amd64 / qemux86-64)
 Home Assistant version: 0.92.2
 Supervisor version: 162

 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.

**Comment by TacticalBill** [comment]
I came to report the same issue. It is happening to me as well. I have the keys_path explicitly called out as /config/firetv/ in the add-on config, but it keeps looking to /root/.android/adbkey  Below are my hardware details. 


Hass.io Add-on: ADB - Android Debug Bridge
The Android Debug Bridge server program

Add-on version: 0.4.0
You are running the latest version of this add-on.
System: HassOS 2.11 (armv7 / raspberrypi3)
Home Assistant version: 0.92.2
Supervisor version: 162

​

**Comment by sinclairpaul** [comment]
It's a symlink from /root/.android to the keys location.  Do you remember which version you upgraded from?  Was it 0.3.1 or earlier?

**Comment by TacticalBill** [comment]
I updated from 0.3.1.  Also to add, I've restarted the ADB addon, Hassio, and the TV several times.

**Comment by sinclairpaul** [comment]
@Hassiopeia Would it be possible for you to backup your keys out of the folder, and restart the addon to see if it does regenerate them?, you can always move them back later?

**Comment by sinclairpaul** [comment]
@Hassiopeia Ignore my request, I can duplicate the issue on a Pi, need to dig some more as to what is failing. 

From manual start up I see * could not start server * after the generate key

@frenck Will need your expertise here, I'm guessing something with the latest ADB package has broken on ARM, I can duplicate this.

**Comment by ghost** [comment]
I have the same issue, I already posted on HA board so do not want too much duplication but my hardware is:`

arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux Arch
python_version | 3.7.3
version | 0.92.2
`

Hope a solution will be soon.

**Comment by arsaboo** [comment]
Can confirm...seeing the same for both my devices on RPi.

**Comment by e-krebs** [comment]
it would be great if a new version rolling back this one would be published while a fix is being developed.
because right now, some of us are stuck on this malfunctioning version with no way to go back to the previous one.

**Comment by frenck** [comment]
I'm going to take a look asap. I do have a day time job.

@e-krebs That is what Hass.io snapshot are for.
