### ISSUE TITLE
Status is always 'Paused'

### ISSUE THREAD

**Issue by simpat1zq** [hassio-addons/addon-adb#13]
# Problem/Motivation

Even when playing a video, the status is paused on the FireTV 4k

## Expected behavior

It should say it's playing a video when it's playing a video. 

## Actual behavior

It just says 'Paused' all the time. 

## Steps to reproduce

Play a video. HA will still say the FireTV is paused. 

## Proposed changes
I don't know if this is a FireTV limitation or now. But it would be nice to be able to run automations based on the state. For example, turn the lights off when state changes to playing, and turn then on when it's stopped or paused.

**Comment by frenck** [comment]
This add-on simply provides a debug bridge. How the data is interpreted is not a concern of this add-on.

So, this should be a report on the HA side.
