### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by geosoftgr** [hassio-addons/addon-adb#15]
I try to connect my android tv box using ADB - Android Debug Bridge in hass.io but i get the folloing error on log file

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: ADB - Android Debug Bridge
 The Android Debug Bridge server program
-----------------------------------------------------------
 Add-on version: 0.5.2
 You are running the latest version of this add-on.
 System: HassOS 2.12  (aarch64 / raspberrypi3-64)
 Home Assistant version: 0.98.2
 Supervisor version: 185
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adb.sh: executing... 
[cont-init.d] adb.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:10:59] INFO: Starting the Android Debug Bridge server...
[22:10:59] INFO: Connecting to device: 192.168.2.44...
unable to connect to 192.168.2.44:5555: Connection refused
[22:12:30] INFO: Connecting to device: 192.168.2.44...
unable to connect to 192.168.2.44:5555: Connection refused
[22:14:00] INFO: Connecting to device: 192.168.2.44...
unable to connect to 192.168.2.44:5555: Connection refused
[22:15:30] INFO: Connecting to device: 192.168.2.44...
unable to connect to 192.168.2.44:5555: Connection refused

any Idea, on what i am doing wrong?

**Comment by sinclairpaul** [comment]
Did you follow the documentation and enable Network Debugging on the device at 192.168.2.44?

**Comment by geosoftgr** [comment]
Hi Paul,
thanks for the replay about my issue,
I have enable the developer option menu,but in the debugging section there is no Network Debugging option, the only one that is available is the USB debugging, but a guess this is only if you connect the device via USB, so maybe i am not able to use this feature on my android TV box device.
 
![Screenshot_20190904-082113](https://user-images.githubusercontent.com/53489029/64252644-30711380-cf24-11e9-91eb-572fca5284e1.png)

**Comment by sinclairpaul** [comment]
Unfortunately it looks like vendors can remove the Network Debugging option, so there is really not much we can do for you in the addon.

**Comment by geosoftgr** [comment]
Thinks Paul, for the assistant,
