### ISSUE TITLE
androidtv.adb_command is missing in services

### ISSUE THREAD

**Issue by adisbr01** [hassio-addons/addon-adb#17]
I have issue after updating HA to 0.1 version.
the service "androidtv.adb_command" is missing.
What could cause this ?
this is my system info:

arch | aarch64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.4
timezone | Asia/Jerusalem
version | 0.100.1
virtualenv | false

**Comment by frenck** [comment]
That is not something the add-on provides.
You are asking about services in Home Assistant. That is where you should be for that specific question.
