### ISSUE TITLE
ModuleNotFoundError: No module named 'androidtv'

### ISSUE THREAD

**Issue by LionelPaulus** [hassio-addons/addon-adb#2]
Hi,

I have added the Hass.io add-on, it seems to be successfully connecting to my Shield TV and now I'm trying to add the component to HA.
So I added the `androidtv.py` file in the correct folder and when I start HA this line of code is causing me the error:

https://github.com/hassio-addons/addon-adb/blob/c367b655d37c6c2afdcec0ab077e8bce3a4a4144/custom_components/media_player/androidtv.py#L166
> ModuleNotFoundError: No module named 'androidtv'

Do you have a solution for me? Thanks in advance!

**Comment by JeffLIrion** [comment]
If you haven't already, try restarting Home Assistant. I've seen it happen where it takes too long to install the required package for the custom component and tries to setup the component before the package is installed, leading to the error message you got.

**Comment by LionelPaulus** [comment]
Thanks, it worked, although I had already tried before 🤷‍♂️
