### ISSUE TITLE
volume_set does not work

### ISSUE THREAD

**Issue by i00** [hassio-addons/addon-adb#21]
# Problem/Motivation
volume_set does not work, the other related volume services do.

## Expected behavior
volume_set should change the volume

## Actual behavior
volume_set does nothing

## Steps to reproduce
Call service volume_set like:
```YAML
entity_id: media_player.bedroom_1_tv_adb
volume_level: 0.6
```

## Proposed changes
Make volume_set work

**Comment by sinclairpaul** [comment]
The addon provides the adb interface, not the integration, I would suggest logging the issue at the HA repo.
