### ISSUE TITLE
ADB through Ethernet adapter

### ISSUE THREAD

**Issue by Devqon** [hassio-addons/addon-adb#22]
[question/support-request]

Maybe not specific for this add-on, but I wondered if you know how to setup the ADB through an Ethernet adapter.

The reason I want to have this setup is for my Xiaomi Mi Box, which only has one USB port and no separate Ethernet port. Therefore I am using an adapter which provides multiple USB ports, as well as an Ethernet port.

If I enable USB debugging however, as required for this add-on, the Ethernet and USB ports won't work.

**Comment by frenck** [comment]
I'm afraid that that box, only WiFi is an option at that point.
Cannot help you there m8, sorry. :(
