### ISSUE TITLE
ADB Bridge DAta/TMP Folder 893.4GB

### ISSUE THREAD

**Issue by eldudemeister** [hassio-addons/addon-adb#23]
# Problem/Motivation

My tmp folder under Data in ADB addon is 893.4gb

## Expected behavior

Addon is running usually but it's filled up my hard drive.

## Actual behavior

Hard drive is full up but addon still functioning. I'm running Core on docker on an Ubuntu 18.04 server. No other issues that I can see. 

## Steps to reproduce

Only installed the addon a couple of days ago, using it to monitor my Shield and one Amazon Fire Stick 4k. No automations being used, only Media Player. 

## Proposed changes

I don't sorry, just hoping for some help.

**Comment by frenck** [comment]
keep open bot, thanks!

**Comment by Scope666** [comment]
I'm also having this issue.  Is there a parameter we can feed this to either stop the logging or put it into an overwrite mode?

**Comment by frenck** [comment]
Can someone please point me towards the exact file location for this? I've seen unable to reproduce this (or I'm not looking at the wrong things).

**Comment by eldudemeister** [comment]
I’ve moved my install to home assistant container and using a separate container for adb bridge now but from what I recall, it was in the temp folder for the addon?

**Comment by iainp999** [comment]
Same issue here.

The folder on my supervised install is at `/home_assistant/config/tmp/tmpavcucaby/a0d7b954_adb.tar.gz`

I noticed that the tarball contains initial entries:

```
drwx------ root/root         0 2020-07-13 22:20 ./
-rw-r--r-- root/root      2150 2020-07-13 22:20 ./addon.json
drwxr-xr-x 1000/1000         0 2020-06-27 13:07 data/
-rw------- 1000/1000      1704 2020-05-24 14:50 data/adbkey
lrwxrwxrwx root/root         0 2020-06-27 13:07 data/data -> /data
-rw-r--r-- 1000/1000       401 2020-06-11 22:39 data/data/discovery.json
drwxr-xr-x 1000/1000         0 2020-06-11 22:30 data/data/apparmor/
drwxr-xr-x 1000/1000         0 2020-06-11 22:30 data/data/apparmor/remove/
drwxr-xr-x 1000/1000         0 2020-06-11 22:30 data/data/apparmor/cache/
drwx------ 1000/1000         0 2020-07-02 06:11 data/data/apparmor/cache/26b63962.0/
-rw-r--r-- 1000/1000      1913 2020-06-11 22:30 data/data/apparmor/cache/26b63962.0/.features
-rw------- root/root     62276 2020-07-02 06:11 data/data/apparmor/cache/26b63962.0/hassio-supervisor
-rw-r--r-- 1000/1000      1982 2020-07-02 06:11 data/data/apparmor/hassio-supervisor
drwxr-xr-x 1000/1000         0 2020-06-05 15:13 data/data/www/
```

and wondering if the symlink is causing a problem?

The rest of the tarball seems to be made up of files under `data/data`.

The file grows at around 1-2GB every couple of minutes until it fills the disk.

**Comment by sinclairpaul** [comment]
Would it be possible to also post your adb integration from HA?, I also haven't been able to reproduce, so wonder if there is a specific command that writes to the log (I will also note its really a development tool so not sure we can do anything about it).

Also can you show the contents of /data/a0d7b954_adb

**Comment by iainp999** [comment]
@sinclairpaul thanks, though unfortunately (fortunately?) it looks like the issue has gone away after I uninstalled and re-installed the addon.

if it happens again then I will post the above.

**Comment by Nailik** [comment]
I had a similar issue when restoring a backup from hassio. There was a folder '/data' inside adb that's a link to a directory above the "adb" directory and it causes a loop in trying to restore.
Also this creates issues in generating backups. I always get this issue:

`20-07-16 04:20:27 ERROR (MainThread) [supervisor.addons.addon] Can't write tarfile <supervisor.utils.tar.SecureTarFile object at 0x7fceba153650>: [Errno 2] No such file or directory: '/data/addons/data/a0d7b954_adb/data/addons/data/a0d7b954_adb/data/addons/data/a0d7b954_adb/data/addons/data/a0d7b954_adb/data/addons/data/a0d7b954_adb/data/addons/data/a0d7b954_adb/data/addons/data/a0d7b954_adb/data/homeassistant/home-assistant_v2.db-wal'
20-07-16 04:20:27 ERROR (MainThread) [supervisor.snapshots.snapshot] Can't make snapshot from a0d7b954_adb`

When i download the backup and i go inside the `adb.tar`, then there is a `data` floder that has homeassistant itself in it
, with the folder `addons` where there is again `adb.tar` and so on ... 


![err2](https://user-images.githubusercontent.com/13292441/87645895-6a1ec780-c74e-11ea-8a2f-dbe62f0d30a8.JPG)
![err1](https://user-images.githubusercontent.com/13292441/87645898-6ab75e00-c74e-11ea-8019-6bb054424ad2.JPG)
