### ISSUE TITLE
Launching App

### ISSUE THREAD

**Issue by JDiaz11** [hassio-addons/addon-adb#24]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by JDiaz11** [comment]
1. 

Hi-

I managed to discern the command for launching Slingplayer using adb shell, it is:
`"adb shell am start -n com.slingmedia.slingPlayerFireTV/com.slingmedia.slingPlayer.Activities.SBNonStreaming"` and it works from my Terminal.

However when I format the service data accordingly:

```
entity_id: media_player.fire_tv
command: "adb shell am start -n com.slingmedia.slingPlayerFireTV/com.slingmedia.slingPlayer.Activities.SBNonStreaming"
```
nothing seems to happen. The other commands work as expected. Is there a special way of formatting adb shell commands for services? Thank you.

**Comment by frenck** [comment]
Hi there,

This is the issue tracker for the bridge itself. For questions on Home Assistant integrations, please check out the Home Assistant community or Home Assistant Discord server.

Thanks 👍
