### ISSUE TITLE
Get information from source

### ISSUE THREAD

**Issue by tibehrius** [hassio-addons/addon-adb#25]
Here I have the same TV integrated with AndroidTV (ADB), and with Bravia PSK. The Android integration shows the name of the App and an image of what is currently being displayed. Just do not inform the name of the video title.

https://prnt.sc/ry0ei5
https://prnt.sc/ry0f6y

Is it possible to get information about what is being displayed, as well as when integrating the Bravia PSK addon?

<blockquote><img src="https://image.prntscr.com/image/K964MiNHTruNfpXge_FVbA.png" width="48" align="right"><div>Lightshot</div><div><strong><a href="https://prnt.sc/ry0ei5">Screenshot</a></strong></div><div>Captured with Lightshot</div></blockquote>
<blockquote><img src="https://image.prntscr.com/image/HeplY2a4Rdy-SIwYfRqcwQ.png" width="48" align="right"><div>Lightshot</div><div><strong><a href="https://prnt.sc/ry0f6y">Screenshot</a></strong></div><div>Captured with Lightshot</div></blockquote>

**Comment by sinclairpaul** [comment]
This would be an issue/question for the HA integration itself, the addon purely provides the ADB interface to connect.  You would need to log it at the Home Assistant Github.
