### ISSUE TITLE
Failed to call service androidtv/send_command. Service not found.

### ISSUE THREAD

**Issue by marcomow** [hassio-addons/addon-adb#27]
Everything worked as expected until I upgraded the supervisor to 0.117, now the androidtv services are just vanished. 

In the addon logs, no errors

 Add-on version: 0.6.3
 You are running the latest version of this add-on.
 System: HassOS 4.15  (armv7 / raspberrypi4)
 Home Assistant Core: 0.117.0
 Home Assistant Supervisor: 2020.10.0

**Comment by frenck** [comment]
I don't see how a service call is related to an add-on. Service are a Home Assistant feature.

**Comment by rursache** [comment]
i'm having the same problem. if the Android tv device shutdown (and so the adb connection will timeout/close), home assistant will stop showing androidtv services and stop receiving events. the 'fix' is to restart the addon.

a guess: the addon doesn't broadcast it's service to HA after a disconnect and a successful reconnect

EDIT: after some research, indeed this addon doesn't seem to be able to add missing services so i opened this issue https://github.com/home-assistant/core/issues/43137

**Comment by rursache** [comment]
i actually fixed the issue by removing this addon and using the default HA implementation for adb - https://github.com/home-assistant/core/issues/43137#issuecomment-727186702
