### ISSUE TITLE
port 5555

### ISSUE THREAD

**Issue by B0ndo2** [hassio-addons/addon-adb#37]
I am not sure where port 5555 is coming from ?. The device is Android 11 and in wifi debug settings the port changes when I initiate pairing

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ADB - Android Debug Bridge
 The Android Debug Bridge server program
-----------------------------------------------------------
 Add-on version: 0.7.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.10  (amd64 / qemux86-64)
 Home Assistant Core: 2021.1.5
 Home Assistant Supervisor: 2021.01.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adb.sh: executing... 
[cont-init.d] adb.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[14:56:08] INFO: Starting the Android Debug Bridge server...
[services.d] done.
[14:56:08] INFO: Connecting to device: 192.168.6.6...
unable to connect to 192.168.6.6:5555: Connection refused
```

**Comment by frenck** [comment]
It the default port `adb` uses to connect to clients:

<https://github.com/hassio-addons/addon-adb/blob/main/adb/rootfs/etc/services.d/adb-connect/run#L26>

This is not controlled by the add-on.

**Comment by B0ndo2** [comment]
Thank you but this means it will not work with Android 11 devices that
change the port !



*Taymour*

**Comment by frenck** [comment]
That is entirely possible. The ADB running in this add-on is pretty old, and there isn't a good updated set available.

Originally this add-on was created to support the android integration in Home Assistant, however, that recently completed the full native protocol implemented.

Considering that, this add-on is likely to be deprecated somewhere soon.

**Comment by B0ndo2** [comment]
The native Androidtv did not work for me



*Taymour*

**Comment by frenck** [comment]
Then this will most certainly not work.
Please file a bug report with the native integration. From the add-on perspective, there are no upgrade paths possible.
