### ISSUE TITLE
androidtv does not generate unique IDs

### ISSUE THREAD

**Issue by PaP-PE** [hassio-addons/addon-adb#45]
# Problem/Motivation
I'm a newbie so please sorry if I am doing wrong...
I get this message in core log
2021-03-01 21:40:52 ERROR (MainThread) [homeassistant.components.media_player] Platform androidtv does not generate unique IDs. ID 1234567890 already exists - ignoring media_player.kingtv

> (Why the issue was filed)
I made the configuration in ADB debug bridge:

devices:
  - 192.168.31.154
  - 192.168.31.150
reconnect_timeout: 90
log_level: debug

## Expected behavior
I don't see how to generate the good ID so that I would not get this message in log.

Thanks in advance

**Comment by frenck** [comment]
> 2021-03-01 21:40:52 ERROR (MainThread) [homeassistant.components.media_player] Platform androidtv does not generate unique IDs. ID 1234567890 already exists - ignoring media_player.kingtv

That is a Home Assistant Core log output message, caused by the Home Assistant Core integration, not the add-on. Please report the issue you are having with Home Assistant Core. Thanks 👍
