### ISSUE TITLE
ERROR keys_path

### ISSUE THREAD

**Issue by viktor6** [hassio-addons/addon-adb#47]
# Problem/Motivation

```
devices:
  - 192.168.0.130
  - 192.168.0.132
reconnect_timeout: 90
log_level: info
keys_path: /config/.androidkeys
```
```
media_player:
  - platform: androidtv
    name: Android TV
    device_class: androidtv
    host: 192.168.0.132
    adbkey: "/config/.androidkeys"
    exclude_unnamed_apps: true
    apps:
      "kodi": "Kodi"
      "tunein": "TuneIn Radio"     
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037
```
log 
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ADB - Android Debug Bridge
 The Android Debug Bridge server program
-----------------------------------------------------------
 Add-on version: 0.7.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.12  (armv7 / raspberrypi3)
 Home Assistant Core: 2021.3.3
 Home Assistant Supervisor: 2021.03.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adb.sh: executing... 
[23:00:16] FATAL: 
[23:00:16] FATAL: It seems like you have configured the "keys_path"
[23:00:16] FATAL: option, unfortunately, the path specified could
[23:00:16] FATAL: not be found.
[23:00:16] FATAL: 
[23:00:16] FATAL: Please double check the add-on configuration.
[23:00:16] FATAL: 
[cont-init.d] adb.sh: exited 1.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23:00:17] INFO: Starting the Android Debug Bridge server...
[23:00:35] INFO: Connecting to device: 192.168.0.132...
connected to 192.168.0.132:5555
[23:02:19] INFO: Connecting to device: 192.168.0.132...
already connected to 192.168.0.132:5555
```

**Comment by sinclairpaul** [comment]
I would suggest not hiding the directory, it's likely the bashio functions can't see it.

**Comment by viktor6** [comment]
> I would suggest not hiding the directory, it's likely the bashio functions can't see it.

Tried the error

**Comment by sinclairpaul** [comment]
I'm not sure what that means, however it also appears that you are mixing the config for the integration and the addon.

I would suggest just using the integration as documented at https://www.home-assistant.io/integrations/androidtv/

**Comment by viktor6** [comment]
> I'm not sure what that means, however it also appears that you are mixing the config for the integration and the addon.
> 
> I would suggest just using the integration as documented at https://www.home-assistant.io/integrations/androidtv/

Do you understand what you are writing? If so, give an example. And I was pointing out the ADB addon error and not the integration

```
Configuration
Note: Remember to restart the add-on when the configuration is changed.

Example add-on configuration, with all available options:

log_level: info
devices:
  - 192.168.1.123
  - 192.168.1.100
reconnect_timeout: 90
keys_path: "/config/.androidkeys"
```
Changed the integration config
Error
media_player:
  - platform: androidtv
    host: 192.168.0.132
    name: Android TV
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037

**Comment by sinclairpaul** [comment]
My mistake, I did not realise that it was in the example config.  However having tested it does work, assuming you have created the directory?

I will still recommend using the Python implementation within the integration.

**Comment by viktor6** [comment]
> My mistake, I did not realise that it was in the example config. However having tested it does work, assuming you have created the directory?
> 
> I will still recommend using the Python implementation within the integration.

I was creating a directory

**Comment by frenck** [comment]
This add-on is now marked deprecated. Closing this issue because of that.
