### ISSUE TITLE
Crash adb addon when sending command

### ISSUE THREAD

**Issue by antoweb** [hassio-addons/addon-adb#59]
# Problem/Motivation

If i send a command unsupported like: shell top -m 10 the the android device in HA stop responding to any further command. I have to restart the adb addon

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Hi there, @antoweb 👋 

This add-on has been deprecated. It is strongly advised not to use it anymore and migrate to the native solution offered by Home Assistant.

This ad-on will not get any fixes or updates anymore.

../Frenck 🚂
