### ISSUE TITLE
88.1 reports wrong keys for custom component 

### ISSUE THREAD

**Issue by capstan1** [hassio-addons/addon-adb#9]
# Problem/Motivation

Since I updated to Home Assistant 0.88.1 I can't use the [custom component for FireTv ](https://github.com/JeffLIrion/homeassistant_native_firetv) which I used with this addon. Logs show:

`
2019-02-28 14:56:50 WARNING (MainThread) [homeassistant.helpers.config_validation] Your configuration contains extra keys that the platform does not support.
Please remove [adb_server_ip], [adb_server_port].  (See /config/configuration.yaml, line 120). 
2019-02-28 14:56:51 WARNING (SyncWorker_3) [root] Couldn't connect to host: 192.168.0.7:5555, error: Broken pipe
2019-02-28 14:56:51 WARNING (SyncWorker_3) [homeassistant.components.media_player.firetv] Could not connect to Fire TV at 192.168.0.7:5555
2019-02-28 21:27:33 WARNING (SyncWorker_9) [homeassistant.helpers.config_validation] Your configuration contains extra keys that the platform does not support.
Please remove [adb_server_ip], [adb_server_port].`

My configuration.yaml is as follows, which is the same as described in the readme of this addon. 

`media_player:
   - platform: firetv
     name: Fire_TV
     host: 192.168.0.7
     adb_server_ip: 127.0.0.1
     adb_server_port: 5037`

So the newest version doesn't support the recommended keys.
Any idea on how to solve this?

**Comment by rocksolid2018** [comment]
custom components needs to change for Android TV.

**Comment by frenck** [comment]
@capstan1 This add-on currently only supplies information on the androidtv component. The firetv component does not support the adb server settings yet. However, this has been updated in HA and is expected to land in a HA release soon.

**Comment by capstan1** [comment]
@frenck Thanks to your reply! I also tried connecting directly with your addon directly and the same error occurs because I need the same settings.
Sorry, but I don't get what you said about updates. What will be updated? And what is or will be the way of integrating adb devices as media players at the moment?

**Comment by frenck** [comment]
I was saying FireTV is not working at this point and there is an update pending from HA to address that in a upcoming version.

**Comment by capstan1** [comment]
okay, thanks for the clarification! So I'll wait!
